// flow-typed signature: 371330506cb946f2a9efae5a51b0485e
// flow-typed version: <<STUB>>/warning_v^4.0.1/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'warning'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'warning' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'warning/warning' {
  declare module.exports: any;
}

// Filename aliases
declare module 'warning/warning.js' {
  declare module.exports: $Exports<'warning/warning'>;
}
